steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/${_PROJECT_ID}/devops-dev/${_IMAGE}:${_COMMIT_SHA}', '.']
  dir: 'app'

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/${_PROJECT_ID}/devops-dev/${_IMAGE}:${_COMMIT_SHA}']

images:
- 'us-central1-docker.pkg.dev/${_PROJECT_ID}/devops-dev/${_IMAGE}:${_COMMIT_SHA}'
