
name: Build and Deploy with Cloud Run to dev environment

on:
  push:
    branches: [ "develop" ]

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID_DEV }}
  GAR_LOCATION: us-central1 # TODO: update region of the Artifact Registry
  REPOSITORY: devops-dev # TODO: update to Artifact Registry docker repository
  IMAGE: php-fpm-app

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    environment: development

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
          credentials_json: '${{ secrets.GCP_SA_KEY_DEV }}'
         
    - name: 'Set up Cloud SDK'
      uses: google-github-actions/setup-gcloud@v2
      with:
          project_id: '${{ secrets.GCP_PROJECT_ID_DEV }}'
    
    - name: 'Authenticate Docker with Artifact Registry'
      run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev


     # Build the Docker image and publish using Cloud Build
    - name: Trigger Cloud Build
      run: |
        gcloud builds submit --config cloudBuild/cloudbuild.yaml --substitutions _PROJECT_ID=${{ secrets.GCP_PROJECT_ID_DEV }},_REPOSITORY=$REPOSITORY,_IMAGE=$IMAGE,_COMMIT_SHA=$GITHUB_SHA,_GAR_LOCATION=$GAR_LOCATION
        

    #  Déploiement de l'application sur Cloud Run avec Terraform
    - name: Deploy app to Cloud Run
      run: |
        cd terraform-deployments/environments/dev
        terraform init
        terraform apply -auto-approve -var "image=$GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE:$GITHUB_SHA"
